spring:
  application:
    name: interview-rabbitmq
  rabbitmq:
    addresses: amqp://huangwj:huangwj@127.0.0.1:5672
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
server:
  port: 8080
logging:
  file:
    path: logs/
