server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.2:8080/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
