spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huangwenjing1231/Mservice
          search-paths: interview-repos
          username: vpvpvpvpvp@126.com
          password: 2666a0483
